version: "2"
run:
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nlreturn
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - tparallel
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
